name: Nick Peng's Blog
url: http://pymumu.github.io
site: pymumu.github.io
author:
    name: Nick Peng
    nickname: pymumu
    github : pymumu
    twitter : 
    googleplus : 105794383153869177146
    facebook : 
permalink: post/:year-:month-:day/:title.html

paginate: 5
paginate_path: "/page:num"
encoding: utf-8
highlighter: pygments

markdown: redcarpet
markdown_ext:  md
redcarpet:
    extensions: [no_intra_emphasis,tables,autolink,fenced_code_blocks,strikethrough,lax_spacing,underline]

exclude: ['README.md', '.*']

